### ISSUE TITLE
Duplicate table in instructions that is out of place. 

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/AZ-030T00-Microsoft-Azure-technologies-for-AWS-architects#17]
# **Module: 12: Implement Azure SQL databases**
#### After Step: 04 Basics tab screenshot.

There is a **table** that is used twice, however the **first instance** is out of place as it is not used in the **BASICS** tab despite being referenced in the instructions. This table is used on the **NETWORKING** tab. Please remove the duplicate instance on the BASICS tab. 

Repro steps:
Under the screenshot after: **Basics** - Fill out mandatory information required on the Basics tab.
Use the table below as a reference for information required at this tab.

![2020-10-15_183831](https://user-images.githubusercontent.com/62302805/96193356-fbe8cd00-0f15-11eb-9118-3468344eb58c.jpg)

URL: https://github.com/MicrosoftLearning/AZ-030T00-Microsoft-Azure-technologies-for-AWS-architects/blob/master/Instructions/Mini-labs/Module%2012/02-MiniLab_Create%20an%20Azure%20SQL%20Database%20Managed%20Instance.md#basics

**Comment by eric-camplin** [comment]
fixed in https://github.com/MicrosoftLearning/AZ-030T00-Microsoft-Azure-technologies-for-AWS-architects/commit/4c97103a2144d146cefbf1c8991d13bc459de887#diff-3bfc80dc38c3f277a44bfe04e3c04bac6b9b36b99392f4cc9b6a7a91e9591550
