### ISSUE TITLE
Mini-lab: Azure Security Center: Recommendations intermittent in Azure and do not match what is in instructions.

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/AZ-030T00-Microsoft-Azure-technologies-for-AWS-architects#18]
# Module: 13 Mini-Labs
### Task: **Add monitoring software via recommendation**

Description of issue

In the instructions the user is meant to add monitoring software via recommendations. 
Recommendations are intermittently showing, sometimes never show. 
When they have shown the do not appear as demonstrated in the screenshot for the lab. there is no "Quick fix" button shown.  It appears azure may have done this automatically designated by the "completed" tags next to the yellow recommendations. 
making the instructions for the lab redundant if so. 
![2020-10-27_185529](https://user-images.githubusercontent.com/62302805/97371389-735c1c00-1887-11eb-9e8f-7137fa27dd48.jpg)

specific instructions for reference:

https://github.com/MicrosoftLearning/AZ-030T00-Microsoft-Azure-technologies-for-AWS-architects/blob/master/Instructions/Mini-labs/Module%2013/01-MiniLab_Azure_Security_Center.md

**Comment by eric-camplin** [comment]
Fixed - see Update 01-MiniLab_Azure_Security_Center.md #20 

Thank you and sorry for the delay in merging fix
